import { v4 as uuidv4 } from 'uuid';

export const FruitsWithCalories = [
    { id: uuidv4(), name: "Apple", calories: 52 },
    { id: uuidv4(), name: "Banana", calories: 89 },
    { id: uuidv4(), name: "Orange", calories: 47 },
    { id: uuidv4(), name: "Grape", calories: 69 },
    { id: uuidv4(), name: "Pineapple", calories: 50 },
    { id: uuidv4(), name: "Strawberry", calories: 33 },
    { id: uuidv4(), name: "Blueberry", calories: 57 },
    { id: uuidv4(), name: "Mango", calories: 60 },
    { id: uuidv4(), name: "Watermelon", calories: 30 },
    { id: uuidv4(), name: "Kiwi", calories: 61 },
    { id: uuidv4(), name: "Pear", calories: 57 },
    { id: uuidv4(), name: "Peach", calories: 39 },
    { id: uuidv4(), name: "Cherry", calories: 50 },
    { id: uuidv4(), name: "Plum", calories: 46 },
    { id: uuidv4(), name: "Lemon", calories: 29 },
    { id: uuidv4(), name: "Lime", calories: 30 },
    { id: uuidv4(), name: "Raspberry", calories: 52 },
    { id: uuidv4(), name: "Blackberry", calories: 43 },
    { id: uuidv4(), name: "Cantaloupe", calories: 34 },
    { id: uuidv4(), name: "Pomegranate", calories: 83 },
    { id: uuidv4(), name: "Coconut", calories: 354 },
    { id: uuidv4(), name: "Avocado", calories: 160 },
    { id: uuidv4(), name: "Fig", calories: 107 },
    { id: uuidv4(), name: "Grapefruit", calories: 52 },
    { id: uuidv4(), name: "Guava", calories: 68 },
    { id: uuidv4(), name: "Honeydew", calories: 64 },
    { id: uuidv4(), name: "Lychee", calories: 66 },
    { id: uuidv4(), name: "Passion Fruit", calories: 97 },
];